# Generated by ChatGPT
# > python clean_latex.py <directory>

import sys
import shutil
import os
from pathlib import Path

def clean_latex_aux_files(directory: str):
    """Delete LaTeX auxiliary files and _minted* directories recursively."""
    extensions = {".aux", ".fdb_latexmk", ".fls", ".log", ".synctex.gz"}
    base_path = Path(directory)

    if not base_path.is_dir():
        print(f"Error: {directory} is not a valid directory.")
        return

    deleted_files = 0
    deleted_dirs = 0

    for root, dirs, files in os.walk(base_path):

        # Remove _minted* directories before descending into them
        for d in list(dirs):
            if d.startswith("_minted"):
                dir_path = Path(root) / d
                try:
                    shutil.rmtree(dir_path)
                    print(f"Deleted directory: {dir_path}")
                    deleted_dirs += 1
                except Exception as e:
                    print(f"Could not delete {dir_path}: {e}")
                dirs.remove(d)  # prevents os.walk from entering it

        # Delete auxiliary files
        for f in files:
            path = Path(root) / f
            if path.suffix in extensions or f.endswith(".synctex.gz"):
                try:
                    path.unlink()
                    print(f"Deleted: {path}")
                    deleted_files += 1
                except Exception as e:
                    print(f"Could not delete {path}: {e}")

    print(f"\nCleanup complete. {deleted_files} files deleted, {deleted_dirs} directories removed.")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: python {sys.argv[0]} <directory>")
        sys.exit(1)

    clean_latex_aux_files(sys.argv[1])