# Generated by ChatGPT
# > python clean_latex.py <filepath>
import os
import sys
from pathlib import Path

def clean_latex_aux_files(directory: str):
    """Delete LaTeX auxiliary files recursively in the given directory."""
    extensions = {".aux", ".fdb_latexmk", ".fls", ".log", ".synctex.gz"}
    base_path = Path(directory)

    if not base_path.is_dir():
        print(f"Error: {directory} is not a valid directory.")
        return

    deleted_count = 0
    for file_path in base_path.rglob("*"):
        if file_path.suffix in extensions or str(file_path).endswith(".synctex.gz"):
            try:
                file_path.unlink()
                print(f"Deleted: {file_path}")
                deleted_count += 1
            except Exception as e:
                print(f"Could not delete {file_path}: {e}")

    print(f"\nCleanup complete. {deleted_count} files deleted.")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: python {sys.argv[0]} <directory_path>")
        sys.exit(1)
    clean_latex_aux_files(sys.argv[1])
